package search

import "marketplace-backend/internal/search"

// audit_fixtures_agency_test.go ships the agency persona's
// 10-profile fixture set used by audit_scenarios_test.go.
//
// Naming pattern (id → dominant feature stress-tested):
//   - 01 AlphaSeniorAgency  — top-rated mature agency
//   - 02 BetaJuniorAgency   — junior agency, lower volume
//   - 03 GammaMarketing     — marketing-focused, available_soon
//   - 04 DeltaNoReviews     — cold start
//   - 05 EpsilonHeavy       — 5 lost disputes (max penalty)
//   - 06 ZetaFeatured       — is_featured = true (dormant V1)
//   - 07 EtaNotAvailable    — top score but Tier B
//   - 08 ThetaNewcomer      — < 60 days (rising-talent eligible)
//   - 09 IotaMidTier        — average baseline
//   - 10 KappaLowComplete   — 30/100 completion (junk text gate)

var agencyFixtures = []search.SearchDocument{
	{
		ID:                     "agency-01:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000001",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Alpha Senior Agency",
		Title:                  "Full-stack delivery agency",
		Skills:                 []string{"react", "node", "aws"},
		SkillsText:             "react node aws full-stack",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.85,
		RatingCount:            60,
		CompletedProjects:      80,
		ProfileCompletionScore: 95,
		LastActiveAt:           daysAgoUnix(1),
		ResponseRate:           0.50,
		IsVerified:             true,
		UniqueClientsCount:     50,
		RepeatClientRate:       0.70,
		UniqueReviewersCount:   55,
		MaxReviewerShare:       0.07,
		ReviewRecencyFactor:    0.90,
		LostDisputesCount:      0,
		AccountAgeDays:         1200,
	},
	{
		ID:                     "agency-02:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000002",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Beta Junior Agency",
		Title:                  "Web development agency",
		Skills:                 []string{"react", "wordpress"},
		SkillsText:             "react wordpress",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.0,
		RatingCount:            12,
		CompletedProjects:      15,
		ProfileCompletionScore: 70,
		LastActiveAt:           daysAgoUnix(5),
		ResponseRate:           0.40,
		IsVerified:             true,
		UniqueClientsCount:     10,
		RepeatClientRate:       0.20,
		UniqueReviewersCount:   12,
		MaxReviewerShare:       0.15,
		ReviewRecencyFactor:    0.75,
		LostDisputesCount:      0,
		AccountAgeDays:         180,
	},
	{
		ID:                     "agency-03:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000003",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Gamma Agency",
		Title:                  "Marketing digital agency",
		Skills:                 []string{"marketing", "seo", "ads"},
		SkillsText:             "marketing seo ads",
		AvailabilityStatus:     "available_soon",
		AvailabilityPriority:   2,
		RatingAverage:          4.7,
		RatingCount:            38,
		CompletedProjects:      45,
		ProfileCompletionScore: 88,
		LastActiveAt:           daysAgoUnix(2),
		ResponseRate:           0.55,
		IsVerified:             true,
		UniqueClientsCount:     30,
		RepeatClientRate:       0.40,
		UniqueReviewersCount:   35,
		MaxReviewerShare:       0.10,
		ReviewRecencyFactor:    0.85,
		LostDisputesCount:      0,
		AccountAgeDays:         800,
	},
	{
		ID:                     "agency-04:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000004",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Delta No Reviews",
		Title:                  "New marketing agency",
		Skills:                 []string{"marketing"},
		SkillsText:             "marketing",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          0,
		RatingCount:            0,
		CompletedProjects:      0,
		ProfileCompletionScore: 65,
		LastActiveAt:           daysAgoUnix(0),
		ResponseRate:           0,
		IsVerified:             false,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   0,
		MaxReviewerShare:       0,
		ReviewRecencyFactor:    0,
		LostDisputesCount:      0,
		AccountAgeDays:         15,
	},
	{
		ID:                     "agency-05:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000005",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Epsilon Heavy Disputes",
		Title:                  "Web development agency",
		Skills:                 []string{"react", "node"},
		SkillsText:             "react node",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.5,
		RatingCount:            20,
		CompletedProjects:      25,
		ProfileCompletionScore: 80,
		LastActiveAt:           daysAgoUnix(3),
		ResponseRate:           0.45,
		IsVerified:             true,
		UniqueClientsCount:     15,
		RepeatClientRate:       0.20,
		UniqueReviewersCount:   18,
		MaxReviewerShare:       0.10,
		ReviewRecencyFactor:    0.80,
		LostDisputesCount:      5, // > 3 → max penalty (capped at 0.30)
		AccountAgeDays:         400,
	},
	{
		ID:                     "agency-06:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000006",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Zeta Featured Override",
		Title:                  "Top marketing agency",
		Skills:                 []string{"marketing", "branding"},
		SkillsText:             "marketing branding",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.5,
		RatingCount:            25,
		CompletedProjects:      30,
		ProfileCompletionScore: 90,
		LastActiveAt:           daysAgoUnix(1),
		ResponseRate:           0.55,
		IsVerified:             true,
		UniqueClientsCount:     20,
		RepeatClientRate:       0.35,
		UniqueReviewersCount:   23,
		MaxReviewerShare:       0.08,
		ReviewRecencyFactor:    0.85,
		LostDisputesCount:      0,
		AccountAgeDays:         500,
		IsFeatured:             true,
	},
	{
		ID:                     "agency-07:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000007",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Eta Not Available",
		Title:                  "Booked agency",
		Skills:                 []string{"react", "design"},
		SkillsText:             "react design",
		AvailabilityStatus:     "not_available",
		AvailabilityPriority:   1,
		RatingAverage:          5.0,
		RatingCount:            100,
		CompletedProjects:      120,
		ProfileCompletionScore: 100,
		LastActiveAt:           daysAgoUnix(0),
		ResponseRate:           0.95,
		IsVerified:             true,
		UniqueClientsCount:     80,
		RepeatClientRate:       0.85,
		UniqueReviewersCount:   95,
		MaxReviewerShare:       0.04,
		ReviewRecencyFactor:    0.95,
		LostDisputesCount:      0,
		AccountAgeDays:         2000,
	},
	{
		ID:                     "agency-08:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000008",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Theta Newcomer",
		Title:                  "Fresh marketing studio",
		Skills:                 []string{"marketing"},
		SkillsText:             "marketing",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.6,
		RatingCount:            8,
		CompletedProjects:      6,
		ProfileCompletionScore: 80,
		LastActiveAt:           daysAgoUnix(1),
		ResponseRate:           0.60,
		IsVerified:             true,
		UniqueClientsCount:     5,
		RepeatClientRate:       0.25,
		UniqueReviewersCount:   8,
		MaxReviewerShare:       0.20,
		ReviewRecencyFactor:    0.95,
		LostDisputesCount:      0,
		AccountAgeDays:         45, // rising-talent age window
	},
	{
		ID:                     "agency-09:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000009",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Iota Mid Tier",
		Title:                  "Web agency",
		Skills:                 []string{"react", "node"},
		SkillsText:             "react node",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.3,
		RatingCount:            18,
		CompletedProjects:      22,
		ProfileCompletionScore: 75,
		LastActiveAt:           daysAgoUnix(4),
		ResponseRate:           0.50,
		IsVerified:             true,
		UniqueClientsCount:     14,
		RepeatClientRate:       0.30,
		UniqueReviewersCount:   16,
		MaxReviewerShare:       0.12,
		ReviewRecencyFactor:    0.78,
		LostDisputesCount:      0,
		AccountAgeDays:         350,
	},
	{
		ID:                     "agency-10:agency",
		OrganizationID:         "aaaaaaa1-0000-0000-0000-000000000010",
		Persona:                search.PersonaAgency,
		IsPublished:            true,
		DisplayName:            "Kappa Low Completion",
		Title:                  "Generic agency",
		Skills:                 []string{"react"},
		SkillsText:             "react",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.5,
		RatingCount:            15,
		CompletedProjects:      10,
		ProfileCompletionScore: 30, // intentionally low
		LastActiveAt:           daysAgoUnix(2),
		ResponseRate:           0.45,
		IsVerified:             true,
		UniqueClientsCount:     8,
		RepeatClientRate:       0.20,
		UniqueReviewersCount:   13,
		MaxReviewerShare:       0.18,
		ReviewRecencyFactor:    0.80,
		LostDisputesCount:      0,
		AccountAgeDays:         300,
	},
}
