package search

import "marketplace-backend/internal/search"

// audit_fixtures_referrer_test.go ships the apporteur d'affaires
// (referrer) persona's 10-profile fixture set. The referrer persona
// is special: per §4.3 of the ranking spec, skills_overlap_ratio
// AND proven_work_score weights are zero — replaced by higher
// rating + response_rate weights. Fixtures lean into that contract.
//
// Naming pattern (id → dominant feature stress-tested):
//   - 01 LambdaSaaSConnector  — top-rated, fast replier (the gold standard)
//   - 02 MuSlowReplier        — same rating but 0.20 response_rate (sinks)
//   - 03 NuIndustrial         — different sector — covers query mismatch
//   - 04 XiNew                — cold start, < 7 days
//   - 05 OmicronNotVerified   — KYC missing → verified_mature = 0
//   - 06 PiSaasSpecialist     — strong cohort baseline
//   - 07 RhoDisputed          — at the saturation point of penalties
//   - 08 SigmaNotAvailable    — Tier B, top-tier score
//   - 09 TauNewcomerVerified  — < 60 days + verified (rising-talent)
//   - 10 UpsilonMid           — average baseline

var referrerFixtures = []search.SearchDocument{
	{
		ID:                     "referrer-01:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000001",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Lambda SaaS Connector",
		Title:                  "B2B SaaS apporteur d'affaires",
		Skills:                 []string{"saas", "b2b"},
		SkillsText:             "saas b2b",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.85,
		RatingCount:            42,
		CompletedProjects:      0,
		ProfileCompletionScore: 90,
		LastActiveAt:           daysAgoUnix(1),
		ResponseRate:           0.95,
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   38,
		MaxReviewerShare:       0.08,
		ReviewRecencyFactor:    0.90,
		LostDisputesCount:      0,
		AccountAgeDays:         900,
	},
	{
		ID:                     "referrer-02:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000002",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Mu Slow Replier",
		Title:                  "Industry connector",
		Skills:                 []string{"saas"},
		SkillsText:             "saas",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.8,
		RatingCount:            30,
		CompletedProjects:      0,
		ProfileCompletionScore: 85,
		LastActiveAt:           daysAgoUnix(7),
		ResponseRate:           0.20, // BAD response rate — should sink
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   28,
		MaxReviewerShare:       0.10,
		ReviewRecencyFactor:    0.80,
		LostDisputesCount:      0,
		AccountAgeDays:         700,
	},
	{
		ID:                     "referrer-03:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000003",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Nu Industrial Apporteur",
		Title:                  "Industrial sector apporteur",
		Skills:                 []string{"industry", "manufacturing"},
		SkillsText:             "industry manufacturing",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.4,
		RatingCount:            18,
		CompletedProjects:      0,
		ProfileCompletionScore: 80,
		LastActiveAt:           daysAgoUnix(2),
		ResponseRate:           0.85,
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   16,
		MaxReviewerShare:       0.12,
		ReviewRecencyFactor:    0.85,
		LostDisputesCount:      0,
		AccountAgeDays:         500,
	},
	{
		ID:                     "referrer-04:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000004",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Xi New Apporteur",
		Title:                  "New apporteur",
		Skills:                 []string{"saas"},
		SkillsText:             "saas",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          0,
		RatingCount:            0,
		CompletedProjects:      0,
		ProfileCompletionScore: 60,
		LastActiveAt:           daysAgoUnix(0),
		ResponseRate:           0,
		IsVerified:             false,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   0,
		MaxReviewerShare:       0,
		ReviewRecencyFactor:    0,
		LostDisputesCount:      0,
		AccountAgeDays:         5,
	},
	{
		ID:                     "referrer-05:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000005",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Omicron Not Verified",
		Title:                  "Mid-tier connector",
		Skills:                 []string{"b2b"},
		SkillsText:             "b2b",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.5,
		RatingCount:            15,
		CompletedProjects:      0,
		ProfileCompletionScore: 70,
		LastActiveAt:           daysAgoUnix(3),
		ResponseRate:           0.85,
		IsVerified:             false, // not KYC verified
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   13,
		MaxReviewerShare:       0.15,
		ReviewRecencyFactor:    0.80,
		LostDisputesCount:      0,
		AccountAgeDays:         200,
	},
	{
		ID:                     "referrer-06:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000006",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Pi Saas Specialist",
		Title:                  "SaaS-only apporteur",
		Skills:                 []string{"saas", "fintech"},
		SkillsText:             "saas fintech",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.75,
		RatingCount:            27,
		CompletedProjects:      0,
		ProfileCompletionScore: 85,
		LastActiveAt:           daysAgoUnix(2),
		ResponseRate:           0.90,
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   25,
		MaxReviewerShare:       0.10,
		ReviewRecencyFactor:    0.88,
		LostDisputesCount:      0,
		AccountAgeDays:         600,
	},
	{
		ID:                     "referrer-07:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000007",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Rho Disputed Apporteur",
		Title:                  "Apporteur",
		Skills:                 []string{"b2b"},
		SkillsText:             "b2b",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.4,
		RatingCount:            22,
		CompletedProjects:      0,
		ProfileCompletionScore: 80,
		LastActiveAt:           daysAgoUnix(5),
		ResponseRate:           0.80,
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   20,
		MaxReviewerShare:       0.12,
		ReviewRecencyFactor:    0.82,
		LostDisputesCount:      3, // 3 × 0.10 = 0.30 (saturation)
		AccountAgeDays:         400,
	},
	{
		ID:                     "referrer-08:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000008",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Sigma Not Available",
		Title:                  "Booked apporteur",
		Skills:                 []string{"b2b"},
		SkillsText:             "b2b",
		AvailabilityStatus:     "not_available",
		AvailabilityPriority:   1,
		RatingAverage:          5.0,
		RatingCount:            50,
		CompletedProjects:      0,
		ProfileCompletionScore: 95,
		LastActiveAt:           daysAgoUnix(1),
		ResponseRate:           0.95,
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   45,
		MaxReviewerShare:       0.06,
		ReviewRecencyFactor:    0.92,
		LostDisputesCount:      0,
		AccountAgeDays:         1500,
	},
	{
		ID:                     "referrer-09:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000009",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Tau Newcomer Verified",
		Title:                  "New apporteur (rising)",
		Skills:                 []string{"saas"},
		SkillsText:             "saas",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.5,
		RatingCount:            6,
		CompletedProjects:      0,
		ProfileCompletionScore: 75,
		LastActiveAt:           daysAgoUnix(0),
		ResponseRate:           0.85,
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   6,
		MaxReviewerShare:       0.18,
		ReviewRecencyFactor:    0.95,
		LostDisputesCount:      0,
		AccountAgeDays:         40,
	},
	{
		ID:                     "referrer-10:referrer",
		OrganizationID:         "ddddddd1-0000-0000-0000-000000000010",
		Persona:                search.PersonaReferrer,
		IsPublished:            true,
		DisplayName:            "Upsilon Mid Apporteur",
		Title:                  "Mid-tier apporteur",
		Skills:                 []string{"b2b"},
		SkillsText:             "b2b",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.4,
		RatingCount:            14,
		CompletedProjects:      0,
		ProfileCompletionScore: 78,
		LastActiveAt:           daysAgoUnix(3),
		ResponseRate:           0.75,
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   12,
		MaxReviewerShare:       0.14,
		ReviewRecencyFactor:    0.80,
		LostDisputesCount:      0,
		AccountAgeDays:         350,
	},
}
