package search

import (
	"strings"

	"marketplace-backend/internal/search"
)

// audit_fixtures_freelance_test.go ships the freelance persona's
// 10-profile fixture set used by audit_scenarios_test.go to
// exercise the rerank pipeline.
//
// Naming pattern (id → dominant feature stress-tested):
//   - 01 SeniorReactParis   — strong text match, top rating, mature
//   - 02 JuniorReactRemote  — same skill, lower rating + younger
//   - 03 GoBackendVeteran   — different skill (go), proven work king
//   - 04 OneStarBurst       — high rating but velocity-attack signal
//   - 05 LowReviewers       — only 2 unique reviewers (floor cap)
//   - 06 NotAvailable       — score-wise great but tier B
//   - 07 ColdStartNewbie    — zero reviews, 4 days old (new-account)
//   - 08 LinkedReviewers    — 60% same-domain reviewers (linked rule)
//   - 09 StuffedKeywords    — skills_text repeats one token (stuffing)
//   - 10 LostDisputes       — 4 lost disputes → max negative penalty

var freelanceFixtures = []search.SearchDocument{
	{
		ID:                     "freelance-01:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000001",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Alice React Paris",
		Title:                  "Senior React Developer",
		Skills:                 []string{"react", "javascript", "typescript"},
		SkillsText:             "react javascript typescript",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.9,
		RatingCount:            32,
		CompletedProjects:      28,
		ProfileCompletionScore: 95,
		LastActiveAt:           daysAgoUnix(1),
		ResponseRate:           0.96,
		IsVerified:             true,
		UniqueClientsCount:     22,
		RepeatClientRate:       0.45,
		UniqueReviewersCount:   28,
		MaxReviewerShare:       0.10,
		ReviewRecencyFactor:    0.85,
		LostDisputesCount:      0,
		AccountAgeDays:         420,
		City:                   "Paris",
		CountryCode:            "FR",
	},
	{
		ID:                     "freelance-02:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000002",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Bob React Remote",
		Title:                  "Junior React Developer",
		Skills:                 []string{"react", "css"},
		SkillsText:             "react css",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.2,
		RatingCount:            7,
		CompletedProjects:      6,
		ProfileCompletionScore: 70,
		LastActiveAt:           daysAgoUnix(7),
		ResponseRate:           0.85,
		IsVerified:             true,
		UniqueClientsCount:     5,
		RepeatClientRate:       0.10,
		UniqueReviewersCount:   7,
		MaxReviewerShare:       0.20,
		ReviewRecencyFactor:    0.70,
		LostDisputesCount:      0,
		AccountAgeDays:         120,
	},
	{
		ID:                     "freelance-03:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000003",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Camille Go Veteran",
		Title:                  "Go Backend Engineer",
		Skills:                 []string{"go", "kubernetes", "postgres"},
		SkillsText:             "go kubernetes postgres",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.6,
		RatingCount:            45,
		CompletedProjects:      62,
		ProfileCompletionScore: 90,
		LastActiveAt:           daysAgoUnix(2),
		ResponseRate:           0.92,
		IsVerified:             true,
		UniqueClientsCount:     38,
		RepeatClientRate:       0.55,
		UniqueReviewersCount:   42,
		MaxReviewerShare:       0.08,
		ReviewRecencyFactor:    0.75,
		LostDisputesCount:      0,
		AccountAgeDays:         900,
	},
	{
		ID:                     "freelance-04:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000004",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Diane One-Star Burst",
		Title:                  "React Developer",
		Skills:                 []string{"react"},
		SkillsText:             "react",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.95,
		RatingCount:            10,
		CompletedProjects:      4,
		ProfileCompletionScore: 60,
		LastActiveAt:           daysAgoUnix(3),
		ResponseRate:           0.80,
		IsVerified:             true,
		UniqueClientsCount:     3,
		RepeatClientRate:       0.05,
		UniqueReviewersCount:   3,
		MaxReviewerShare:       0.40,
		ReviewRecencyFactor:    0.95,
		LostDisputesCount:      0,
		AccountAgeDays:         60,
	},
	{
		ID:                     "freelance-05:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000005",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Eva Low Reviewers",
		Title:                  "React Developer",
		Skills:                 []string{"react", "vue"},
		SkillsText:             "react vue",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          5.0,
		RatingCount:            5,
		CompletedProjects:      4,
		ProfileCompletionScore: 75,
		LastActiveAt:           daysAgoUnix(5),
		ResponseRate:           0.75,
		IsVerified:             true,
		UniqueClientsCount:     2,
		RepeatClientRate:       0.0,
		UniqueReviewersCount:   2,
		MaxReviewerShare:       0.50,
		ReviewRecencyFactor:    0.80,
		LostDisputesCount:      0,
		AccountAgeDays:         150,
	},
	{
		ID:                     "freelance-06:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000006",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Felix Not Available",
		Title:                  "Senior Architect",
		Skills:                 []string{"react", "aws", "kubernetes"},
		SkillsText:             "react aws kubernetes",
		AvailabilityStatus:     "not_available",
		AvailabilityPriority:   1,
		RatingAverage:          4.95,
		RatingCount:            80,
		CompletedProjects:      90,
		ProfileCompletionScore: 100,
		LastActiveAt:           daysAgoUnix(1),
		ResponseRate:           0.99,
		IsVerified:             true,
		UniqueClientsCount:     50,
		RepeatClientRate:       0.7,
		UniqueReviewersCount:   75,
		MaxReviewerShare:       0.05,
		ReviewRecencyFactor:    0.90,
		LostDisputesCount:      0,
		AccountAgeDays:         1500,
	},
	{
		ID:                     "freelance-07:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000007",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Gina Cold Start Newbie",
		Title:                  "Junior React Developer",
		Skills:                 []string{"react", "html"},
		SkillsText:             "react html",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          0,
		RatingCount:            0,
		CompletedProjects:      0,
		ProfileCompletionScore: 80,
		LastActiveAt:           daysAgoUnix(0),
		ResponseRate:           0,
		IsVerified:             true,
		UniqueClientsCount:     0,
		RepeatClientRate:       0,
		UniqueReviewersCount:   0,
		MaxReviewerShare:       0,
		ReviewRecencyFactor:    0,
		LostDisputesCount:      0,
		AccountAgeDays:         4,
	},
	{
		ID:                     "freelance-08:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000008",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Hugo Linked Reviewers",
		Title:                  "React Engineer",
		Skills:                 []string{"react", "node"},
		SkillsText:             "react node",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.85,
		RatingCount:            10,
		CompletedProjects:      8,
		ProfileCompletionScore: 70,
		LastActiveAt:           daysAgoUnix(2),
		ResponseRate:           0.88,
		IsVerified:             true,
		UniqueClientsCount:     7,
		RepeatClientRate:       0.20,
		UniqueReviewersCount:   10,
		MaxReviewerShare:       0.15,
		ReviewRecencyFactor:    0.90,
		LostDisputesCount:      0,
		AccountAgeDays:         180,
	},
	{
		ID:                     "freelance-09:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000009",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Ivan Stuffed Keywords",
		Title:                  "React Master",
		Skills:                 []string{"react"},
		// Repetition triggers stuffing rule (§7.1: max repetition > 5).
		SkillsText:             strings.Repeat("react ", 12) + "react",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.7,
		RatingCount:            18,
		CompletedProjects:      14,
		ProfileCompletionScore: 70,
		LastActiveAt:           daysAgoUnix(3),
		ResponseRate:           0.85,
		IsVerified:             true,
		UniqueClientsCount:     12,
		RepeatClientRate:       0.30,
		UniqueReviewersCount:   16,
		MaxReviewerShare:       0.10,
		ReviewRecencyFactor:    0.85,
		LostDisputesCount:      0,
		AccountAgeDays:         300,
	},
	{
		ID:                     "freelance-10:freelance",
		OrganizationID:         "fffffff1-0000-0000-0000-000000000010",
		Persona:                search.PersonaFreelance,
		IsPublished:            true,
		DisplayName:            "Jane Lost Disputes",
		Title:                  "React Developer",
		Skills:                 []string{"react", "redux"},
		SkillsText:             "react redux",
		AvailabilityStatus:     "available_now",
		AvailabilityPriority:   3,
		RatingAverage:          4.7,
		RatingCount:            22,
		CompletedProjects:      18,
		ProfileCompletionScore: 85,
		LastActiveAt:           daysAgoUnix(2),
		ResponseRate:           0.90,
		IsVerified:             true,
		UniqueClientsCount:     14,
		RepeatClientRate:       0.40,
		UniqueReviewersCount:   20,
		MaxReviewerShare:       0.10,
		ReviewRecencyFactor:    0.85,
		LostDisputesCount:      4, // → 4 × 0.10 = 0.40, capped at 0.30 (max penalty)
		AccountAgeDays:         600,
	},
}
