package search

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"marketplace-backend/internal/search"
)

// service.go is the application-layer wrapper around the
// per-persona scoped Typesense clients. It owns the concrete query
// shape (query_by, facet_by, sort_by, highlight fields) and parses
// the raw Typesense response into a typed result struct.
//
// Handlers depend on *Service, never directly on
// search.PersonaScopedClient — that gives us a single place to add
// caching, rate limiting, or query rewriting in future phases
// without touching every call site.

// PersonaQueryClient is the narrow interface the service depends
// on. Defined locally instead of importing
// search.PersonaScopedClient directly so unit tests can drop a
// fake in via constructor injection.
type PersonaQueryClient interface {
	Persona() search.Persona
	Query(ctx context.Context, params search.SearchParams) (json.RawMessage, error)
}

// ServiceDeps groups the constructor inputs. The service holds
// one client per persona; missing personas return ErrPersonaNotConfigured
// so the handler can surface a clean 404.
//
// Embedder + Analytics are optional. When Embedder is nil the service
// falls back to keyword-only search (BM25); when Analytics is nil the
// service skips the fire-and-forget capture step. This lets the
// service degrade gracefully when OpenAI or Postgres is unavailable.
type ServiceDeps struct {
	Freelance PersonaQueryClient
	Agency    PersonaQueryClient
	Referrer  PersonaQueryClient
	Embedder  search.EmbeddingsClient
	Analytics AnalyticsRecorder
	Logger    *slog.Logger
}

// AnalyticsRecorder is the port the service uses to capture each
// search into the search_queries table. Declared locally (consumer-
// side interface) so the service package stays independent of any
// concrete analytics implementation.
type AnalyticsRecorder interface {
	CaptureSearch(ctx context.Context, event AnalyticsEvent)
}

// AnalyticsEvent is the per-search payload posted to the recorder.
// A superset of the search_queries columns so the recorder can
// persist any subset it wants.
type AnalyticsEvent struct {
	SearchID     string
	UserID       string
	SessionID    string
	Query        string
	FilterBy     string
	SortBy       string
	Persona      string
	ResultsCount int
	LatencyMs    int
}

// Service is the application service for the public search query
// path. Methods are safe for concurrent use because every dependency
// they touch is itself concurrent-safe.
type Service struct {
	clients   map[search.Persona]PersonaQueryClient
	embedder  search.EmbeddingsClient
	analytics AnalyticsRecorder
	logger    *slog.Logger
}

// NewService wires the service from its dependency struct. Nil
// entries are silently dropped so the caller can opt out of any
// persona at boot time (e.g. when a worktree is testing only the
// freelance flow).
func NewService(deps ServiceDeps) *Service {
	clients := make(map[search.Persona]PersonaQueryClient, 3)
	if deps.Freelance != nil {
		clients[search.PersonaFreelance] = deps.Freelance
	}
	if deps.Agency != nil {
		clients[search.PersonaAgency] = deps.Agency
	}
	if deps.Referrer != nil {
		clients[search.PersonaReferrer] = deps.Referrer
	}
	logger := deps.Logger
	if logger == nil {
		logger = slog.Default()
	}
	return &Service{
		clients:   clients,
		embedder:  deps.Embedder,
		analytics: deps.Analytics,
		logger:    logger,
	}
}

// HasPersona reports whether the service has a client wired for the
// given persona. Used by the scoped-key handler to decide whether
// to short-circuit with a 404.
func (s *Service) HasPersona(p search.Persona) bool {
	_, ok := s.clients[p]
	return ok
}

// ErrPersonaNotConfigured signals that the requested persona does
// not have a wired client — usually because the search engine is
// disabled or a dev environment opted out.
var ErrPersonaNotConfigured = fmt.Errorf("search: persona is not configured")

// QueryInput is the per-request payload posted to Service.Query.
// Field semantics mirror the public API: every field is optional,
// and the service applies sane defaults (per_page=20).
//
// Cursor is an opaque string generated by the previous page; empty
// means "first page". Page + PerPage remain available for the
// non-paginated use cases (admin dashboards, golden tests) but the
// public API should always use Cursor.
type QueryInput struct {
	Persona   search.Persona
	Query     string
	Filters   FilterInput
	SortBy    string
	Page      int
	PerPage   int
	Cursor    string
	UserID    string // optional, captured in analytics
	SessionID string // optional, captured in analytics
}

// QueryResult is the typed payload returned to handlers and (via
// JSON) to the frontend SSR fallback. It is a strict subset of the
// raw Typesense response — the embedding vectors are stripped to
// keep the payload small and the field is omitted entirely.
//
// Hybrid reports whether the query blended BM25 + vector cosine on
// this call. Handlers use it for structured logging; the frontend
// ignores the field. Deliberately NOT json-serialised so no public
// consumer couples to it.
type QueryResult struct {
	SearchID       string                    `json:"search_id"`
	Documents      []search.SearchDocument   `json:"documents"`
	Found          int                       `json:"found"`
	OutOf          int                       `json:"out_of"`
	Page           int                       `json:"page"`
	PerPage        int                       `json:"per_page"`
	SearchTimeMs   int                       `json:"search_time_ms"`
	FacetCounts    map[string]map[string]int `json:"facet_counts"`
	CorrectedQuery string                    `json:"corrected_query,omitempty"`
	Highlights     []map[string]string       `json:"highlights"`
	NextCursor     string                    `json:"next_cursor,omitempty"`
	HasMore        bool                      `json:"has_more"`
	Hybrid         bool                      `json:"-"`
}

// Default page sizing constants. PerPage is capped at MaxPerPage so
// a misbehaving client cannot ask for 10k documents in one call.
const (
	DefaultPage    = 1
	DefaultPerPage = 20
	MaxPerPage     = 60
)

// Query runs the search against the persona-scoped client and
// parses the response. Empty Query strings are interpreted as
// "match all" via the `*` wildcard so the listing pages can render
// without a typed query.
//
// Pipeline:
//  1. Resolve page from cursor (opaque base64).
//  2. Optionally embed the query text when hybrid search is enabled
//     and the user typed something (we skip embeddings on `q=*` so
//     vector distance does not dominate the listing page).
//  3. Execute Typesense search.
//  4. Parse + decorate the response (search_id, next_cursor, has_more).
//  5. Fire-and-forget analytics capture.
func (s *Service) Query(ctx context.Context, input QueryInput) (*QueryResult, error) {
	client, ok := s.clients[input.Persona]
	if !ok {
		return nil, fmt.Errorf("search query: %w: %s", ErrPersonaNotConfigured, input.Persona)
	}

	page, err := resolvePage(input)
	if err != nil {
		return nil, fmt.Errorf("search query: %w", err)
	}
	vectorQuery := s.maybeVectorQuery(ctx, input)
	params := s.buildSearchParams(input, page, vectorQuery != "")
	params.VectorQuery = vectorQuery

	start := time.Now()
	raw, err := client.Query(ctx, params)
	latency := time.Since(start)
	if err != nil {
		return nil, fmt.Errorf("search query: %w", err)
	}
	result, err := parseQueryResult(raw)
	if err != nil {
		return nil, err
	}

	result.Hybrid = vectorQuery != ""
	s.decorateResult(result, input, params)
	s.captureAnalytics(ctx, input, result, params, latency)
	return result, nil
}

// decorateResult fills the phase 3 metadata (SearchID, NextCursor,
// HasMore). Pulled out of Query so the hot path stays flat.
//
// Typesense sometimes omits per_page from the response envelope; we
// fall back to the params we sent so has_more math stays correct.
func (s *Service) decorateResult(result *QueryResult, input QueryInput, params search.SearchParams) {
	result.SearchID = NewSearchID(input, params, time.Now())
	perPage := result.PerPage
	if perPage == 0 {
		perPage = params.PerPage
	}
	if result.PerPage == 0 {
		result.PerPage = perPage
	}
	page := result.Page
	if page == 0 {
		page = params.Page
	}
	if result.Page == 0 {
		result.Page = page
	}
	totalLoaded := page * perPage
	result.HasMore = totalLoaded < result.Found
	if result.HasMore {
		result.NextCursor = EncodeCursor(Cursor{Page: page + 1})
	}
}

// captureAnalytics fires a fire-and-forget CaptureSearch. Never
// blocks the caller and never surfaces errors — analytics must not
// degrade the user-facing search path.
func (s *Service) captureAnalytics(ctx context.Context, input QueryInput, result *QueryResult, params search.SearchParams, latency time.Duration) {
	if s.analytics == nil {
		return
	}
	evt := AnalyticsEvent{
		SearchID:     result.SearchID,
		UserID:       input.UserID,
		SessionID:    input.SessionID,
		Query:        params.Q,
		FilterBy:     params.FilterBy,
		SortBy:       params.SortBy,
		Persona:      string(input.Persona),
		ResultsCount: result.Found,
		LatencyMs:    int(latency.Milliseconds()),
	}
	s.analytics.CaptureSearch(ctx, evt)
}

// maybeVectorQuery returns the Typesense hybrid `vector_query`
// parameter when the user typed a real query AND an embedder is
// wired. Empty query (match-all) returns "" so the listing page
// stays keyword-first.
func (s *Service) maybeVectorQuery(ctx context.Context, input QueryInput) string {
	if s.embedder == nil {
		return ""
	}
	q := strings.TrimSpace(input.Query)
	if q == "" || q == "*" {
		return ""
	}
	vec, err := s.embedder.Embed(ctx, q)
	if err != nil {
		s.logger.Warn("search: embedding failed, falling back to BM25 only",
			"error", err, "persona", input.Persona)
		return ""
	}
	return search.FormatVectorQuery(vec, HybridK)
}

// HybridK is the number of vector-search candidates Typesense
// considers in the hybrid blend. 20 matches the phase 3 spec.
const HybridK = 20

// buildSearchParams assembles the Typesense query parameters from
// the input + sane defaults. Extracted so tests can pin the exact
// wire format the service produces.
//
// `hybridActive` toggles the hybrid-specific wire format: embedding
// in query_by + _vector_distance in sort_by. Must match whether the
// caller is going to set params.VectorQuery — mismatching the two
// tripwires Typesense's validation and returns 400.
func (s *Service) buildSearchParams(input QueryInput, page int, hybridActive bool) search.SearchParams {
	q := strings.TrimSpace(input.Query)
	if q == "" {
		q = "*"
	}
	perPage := input.PerPage
	if perPage <= 0 {
		perPage = DefaultPerPage
	}
	if perPage > MaxPerPage {
		perPage = MaxPerPage
	}

	sortBy := strings.TrimSpace(input.SortBy)
	if sortBy == "" {
		if hybridActive {
			sortBy = search.DefaultSortByHybrid()
		} else {
			sortBy = search.DefaultSortBy()
		}
	}

	// Hybrid query_by: when hybrid is active we include the embedding
	// field so Typesense blends BM25 + vector cosine natively. On
	// match-all (q=*) or when no embedder is wired, we skip it —
	// vector ranking with no text to embed is noise.
	queryBy := defaultQueryBy
	numTypos := defaultNumTypos
	if hybridActive {
		queryBy = defaultQueryBy + ",embedding"
		// embedding is a vector field — num_typos must match query_by
		// length. A vector field ignores the value; we append "0" for
		// Typesense to accept the command.
		numTypos = defaultNumTypos + ",0"
	}

	return search.SearchParams{
		Q:                   q,
		QueryBy:             queryBy,
		FilterBy:            BuildFilterBy(input.Filters),
		FacetBy:             defaultFacetBy,
		SortBy:              sortBy,
		Page:                page,
		PerPage:             perPage,
		ExcludeFields:       "embedding",
		HighlightFields:     "display_name,title,skills_text",
		HighlightFullFields: "display_name,title",
		// Typesense requires num_typos to either be a single value
		// applied to every query_by field or a comma-separated list
		// with the SAME length as query_by. We use a per-field list
		// so display_name + title tolerate two typos but
		// skills_text + city are strict (skills are technical terms
		// where typos usually mean a different concept).
		NumTypos:       numTypos,
		MaxFacetValues: 40,
	}
}

// defaultQueryBy is the comma-separated list of fields the query
// term hits. Order matters: Typesense weights earlier fields more
// heavily so display_name + title get the top rank.
//
// IMPORTANT: keep this in sync with the NumTypos field count above.
const defaultQueryBy = "display_name,title,skills_text,city"

// defaultNumTypos matches the four defaultQueryBy fields. See
// buildSearchParams for why each slot has its specific budget.
const defaultNumTypos = "2,2,1,1"

// defaultFacetBy is the list of fields the response should compute
// counts for. Persona is intentionally excluded — the scoped client
// already locks it.
const defaultFacetBy = "availability_status,city,country_code,languages_professional," +
	"expertise_domains,skills,work_mode,is_verified,is_top_rated,pricing_currency"
