import type { Conversation, Message } from "./types"

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "1",
    name: "Jean Dupont",
    role: "freelancer",
    lastMessage: "I'll send the mockups tomorrow",
    lastMessageAt: "10:30",
    avatar: null,
    unread: 2,
    online: true,
  },
  {
    id: "2",
    name: "AgenceWeb Paris",
    role: "agency",
    lastMessage: "The project is on track",
    lastMessageAt: "Yesterday",
    avatar: null,
    unread: 0,
    online: false,
  },
  {
    id: "3",
    name: "TechCorp",
    role: "enterprise",
    lastMessage: null,
    lastMessageAt: null,
    avatar: null,
    unread: 0,
    online: true,
  },
  {
    id: "4",
    name: "Marie Laurent",
    role: "freelancer",
    lastMessage: "Can we schedule a call?",
    lastMessageAt: "Mon",
    avatar: null,
    unread: 1,
    online: false,
  },
  {
    id: "5",
    name: "Studio Pixel",
    role: "agency",
    lastMessage: "Invoice sent for Q1",
    lastMessageAt: "Mar 20",
    avatar: null,
    unread: 0,
    online: true,
  },
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: "m1",
    conversationId: "1",
    senderId: "other",
    content: "Hi! I wanted to discuss the project timeline.",
    sentAt: "09:15",
    isOwn: false,
  },
  {
    id: "m2",
    conversationId: "1",
    senderId: "me",
    content: "Sure, I'm available this afternoon. What works for you?",
    sentAt: "09:22",
    isOwn: true,
  },
  {
    id: "m3",
    conversationId: "1",
    senderId: "other",
    content: "3pm would be great. I'll prepare the mockups beforehand.",
    sentAt: "09:30",
    isOwn: false,
  },
  {
    id: "m4",
    conversationId: "1",
    senderId: "me",
    content: "Perfect, I'll send you the brief document before then.",
    sentAt: "09:45",
    isOwn: true,
  },
  {
    id: "m5",
    conversationId: "1",
    senderId: "other",
    content: "I'll send the mockups tomorrow",
    sentAt: "10:30",
    isOwn: false,
  },
]
