import 'package:freezed_annotation/freezed_annotation.dart';

part 'current_month_aggregate.freezed.dart';

/// One milestone-fee entry feeding the not-yet-issued monthly commission
/// invoice.
///
/// All cents are non-negative integers in the org's billing currency.
/// [proposalAmountCents] is the gross milestone amount; [platformFeeCents]
/// is the slice the platform retains. The (gross - fee) delta is what the
/// provider already received in their wallet.
@freezed
class CurrentMonthLine with _$CurrentMonthLine {
  const factory CurrentMonthLine({
    required String milestoneId,
    required String paymentRecordId,
    required DateTime releasedAt,
    required int platformFeeCents,
    required int proposalAmountCents,
  }) = _CurrentMonthLine;
}

/// Live aggregate of the current calendar month's commission activity,
/// returned by `GET /api/v1/me/invoicing/current-month`.
///
/// This is a preview of what the next consolidated monthly-commission
/// invoice will look like; the actual invoice document is generated by
/// the scheduler at month-end (see Phase 5). Empty months return zeroed
/// totals + an empty [lines] array.
@freezed
class CurrentMonthAggregate with _$CurrentMonthAggregate {
  const factory CurrentMonthAggregate({
    required DateTime periodStart,
    required DateTime periodEnd,
    required int milestoneCount,
    required int totalFeeCents,
    required List<CurrentMonthLine> lines,
  }) = _CurrentMonthAggregate;
}
