// Part 2 of the curated skills catalog. See skills.go for the package
// documentation and the invariants enforced by the test suite. This
// file holds the last eight expertise sections only because a single
// file would exceed the 600-line project limit. Placement of entries
// in skills.go vs. skills_part2.go is purely a readability split —
// the test suite counts distribution via the combined CuratedSkills
// slice.
package seed

// skillsPart2 holds the last eight expertise sections in the same
// order as expertise.All (writing_translation through hr_recruitment).
var skillsPart2 = []SeedSkill{
	// ---------------------------------------------------------------
	// writing_translation (target ~20)
	// ---------------------------------------------------------------
	{SkillText: "technical writing", DisplayText: "Technical Writing", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "blog writing", DisplayText: "Blog Writing", ExpertiseKeys: []string{"writing_translation", "marketing_growth"}},
	{SkillText: "seo copywriting", DisplayText: "SEO Copywriting", ExpertiseKeys: []string{"writing_translation", "marketing_growth"}},
	{SkillText: "ghostwriting", DisplayText: "Ghostwriting", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "scriptwriting", DisplayText: "Scriptwriting", ExpertiseKeys: []string{"writing_translation", "video_motion"}},
	{SkillText: "ux writing", DisplayText: "UX Writing", ExpertiseKeys: []string{"writing_translation", "design_ui_ux"}},
	{SkillText: "whitepaper writing", DisplayText: "Whitepaper Writing", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "case study writing", DisplayText: "Case Study Writing", ExpertiseKeys: []string{"writing_translation", "marketing_growth"}},
	{SkillText: "editing & proofreading", DisplayText: "Editing & Proofreading", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "translation english-french", DisplayText: "Translation English-French", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "translation french-english", DisplayText: "Translation French-English", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "spanish translation", DisplayText: "Spanish Translation", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "german translation", DisplayText: "German Translation", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "italian translation", DisplayText: "Italian Translation", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "arabic translation", DisplayText: "Arabic Translation", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "localization", DisplayText: "Localization", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "transcreation", DisplayText: "Transcreation", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "subtitling", DisplayText: "Subtitling", ExpertiseKeys: []string{"writing_translation", "video_motion"}},
	{SkillText: "academic writing", DisplayText: "Academic Writing", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "grant writing", DisplayText: "Grant Writing", ExpertiseKeys: []string{"writing_translation"}},
	{SkillText: "press release writing", DisplayText: "Press Release Writing", ExpertiseKeys: []string{"writing_translation", "marketing_growth"}},
	{SkillText: "product description writing", DisplayText: "Product Description Writing", ExpertiseKeys: []string{"writing_translation", "marketing_growth"}},

	// ---------------------------------------------------------------
	// business_dev_sales (target ~25)
	// ---------------------------------------------------------------
	{SkillText: "b2b sales", DisplayText: "B2B Sales", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "outbound prospecting", DisplayText: "Outbound Prospecting", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "inbound sales", DisplayText: "Inbound Sales", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "cold emailing", DisplayText: "Cold Emailing", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "linkedin prospecting", DisplayText: "LinkedIn Prospecting", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "sales enablement", DisplayText: "Sales Enablement", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "sdr operations", DisplayText: "SDR Operations", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "account management", DisplayText: "Account Management", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "key account management", DisplayText: "Key Account Management", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "strategic partnerships", DisplayText: "Strategic Partnerships", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "channel sales", DisplayText: "Channel Sales", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "sales operations", DisplayText: "Sales Operations", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "revenue operations", DisplayText: "Revenue Operations", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "pipeline management", DisplayText: "Pipeline Management", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "salesforce crm", DisplayText: "Salesforce CRM", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "pipedrive", DisplayText: "Pipedrive", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "lemlist", DisplayText: "Lemlist", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "apollo.io", DisplayText: "Apollo.io", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "linkedin sales navigator", DisplayText: "LinkedIn Sales Navigator", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "rfp management", DisplayText: "RFP Management", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "contract negotiation", DisplayText: "Contract Negotiation", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "sales forecasting", DisplayText: "Sales Forecasting", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "customer success", DisplayText: "Customer Success", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "churn reduction", DisplayText: "Churn Reduction", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "business development", DisplayText: "Business Development", ExpertiseKeys: []string{"business_dev_sales"}},
	{SkillText: "lead generation", DisplayText: "Lead Generation", ExpertiseKeys: []string{"business_dev_sales", "marketing_growth"}},

	// ---------------------------------------------------------------
	// consulting_strategy (target ~25)
	// ---------------------------------------------------------------
	{SkillText: "business strategy", DisplayText: "Business Strategy", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "go-to-market strategy", DisplayText: "Go-to-Market Strategy", ExpertiseKeys: []string{"consulting_strategy", "marketing_growth"}},
	{SkillText: "market research", DisplayText: "Market Research", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "competitive analysis", DisplayText: "Competitive Analysis", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "business model canvas", DisplayText: "Business Model Canvas", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "financial modeling", DisplayText: "Financial Modeling", ExpertiseKeys: []string{"consulting_strategy", "finance_accounting"}},
	{SkillText: "mergers & acquisitions", DisplayText: "Mergers & Acquisitions", ExpertiseKeys: []string{"consulting_strategy", "finance_accounting"}},
	{SkillText: "due diligence", DisplayText: "Due Diligence", ExpertiseKeys: []string{"consulting_strategy", "finance_accounting"}},
	{SkillText: "digital transformation", DisplayText: "Digital Transformation", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "change management", DisplayText: "Change Management", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "lean management", DisplayText: "Lean Management", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "six sigma", DisplayText: "Six Sigma", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "process optimization", DisplayText: "Process Optimization", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "okr implementation", DisplayText: "OKR Implementation", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "balanced scorecard", DisplayText: "Balanced Scorecard", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "innovation strategy", DisplayText: "Innovation Strategy", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "sustainability strategy", DisplayText: "Sustainability Strategy", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "csr strategy", DisplayText: "CSR Strategy", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "esg reporting", DisplayText: "ESG Reporting", ExpertiseKeys: []string{"consulting_strategy", "finance_accounting"}},
	{SkillText: "startup advisory", DisplayText: "Startup Advisory", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "fundraising strategy", DisplayText: "Fundraising Strategy", ExpertiseKeys: []string{"consulting_strategy", "finance_accounting"}},
	{SkillText: "pitch deck creation", DisplayText: "Pitch Deck Creation", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "corporate strategy", DisplayText: "Corporate Strategy", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "internationalization strategy", DisplayText: "Internationalization Strategy", ExpertiseKeys: []string{"consulting_strategy"}},
	{SkillText: "pricing strategy", DisplayText: "Pricing Strategy", ExpertiseKeys: []string{"consulting_strategy", "marketing_growth"}},
	{SkillText: "benchmarking", DisplayText: "Benchmarking", ExpertiseKeys: []string{"consulting_strategy"}},

	// ---------------------------------------------------------------
	// product_ux_research (target ~20)
	// ---------------------------------------------------------------
	{SkillText: "product management", DisplayText: "Product Management", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "product discovery", DisplayText: "Product Discovery", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "product roadmapping", DisplayText: "Product Roadmapping", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "user research", DisplayText: "User Research", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "usability testing", DisplayText: "Usability Testing", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "user interviews", DisplayText: "User Interviews", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "surveys & questionnaires", DisplayText: "Surveys & Questionnaires", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "persona design", DisplayText: "Persona Design", ExpertiseKeys: []string{"product_ux_research", "design_ui_ux"}},
	{SkillText: "customer journey mapping", DisplayText: "Customer Journey Mapping", ExpertiseKeys: []string{"product_ux_research", "design_ui_ux"}},
	{SkillText: "jobs-to-be-done framework", DisplayText: "Jobs-to-be-Done Framework", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "product analytics", DisplayText: "Product Analytics", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "notion", DisplayText: "Notion", ExpertiseKeys: []string{"product_ux_research", "ops_admin_support"}},
	{SkillText: "linear", DisplayText: "Linear", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "jira", DisplayText: "Jira", ExpertiseKeys: []string{"product_ux_research", "ops_admin_support"}},
	{SkillText: "productboard", DisplayText: "Productboard", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "maze", DisplayText: "Maze", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "hotjar", DisplayText: "Hotjar", ExpertiseKeys: []string{"product_ux_research", "marketing_growth"}},
	{SkillText: "agile methodology", DisplayText: "Agile Methodology", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "scrum", DisplayText: "Scrum", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "kanban", DisplayText: "Kanban", ExpertiseKeys: []string{"product_ux_research"}},
	{SkillText: "design thinking", DisplayText: "Design Thinking", ExpertiseKeys: []string{"product_ux_research", "design_ui_ux"}},
	{SkillText: "service design", DisplayText: "Service Design", ExpertiseKeys: []string{"product_ux_research", "design_ui_ux"}},
	{SkillText: "qualitative research", DisplayText: "Qualitative Research", ExpertiseKeys: []string{"product_ux_research"}},

	// ---------------------------------------------------------------
	// ops_admin_support (target ~20)
	// ---------------------------------------------------------------
	{SkillText: "executive assistance", DisplayText: "Executive Assistance", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "office management", DisplayText: "Office Management", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "virtual assistance", DisplayText: "Virtual Assistance", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "calendar management", DisplayText: "Calendar Management", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "travel coordination", DisplayText: "Travel Coordination", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "expense reporting", DisplayText: "Expense Reporting", ExpertiseKeys: []string{"ops_admin_support", "finance_accounting"}},
	{SkillText: "procurement", DisplayText: "Procurement", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "vendor management", DisplayText: "Vendor Management", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "supply chain management", DisplayText: "Supply Chain Management", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "logistics", DisplayText: "Logistics", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "customer support", DisplayText: "Customer Support", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "zendesk", DisplayText: "Zendesk", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "intercom", DisplayText: "Intercom", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "freshdesk", DisplayText: "Freshdesk", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "google workspace", DisplayText: "Google Workspace", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "microsoft 365", DisplayText: "Microsoft 365", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "microsoft excel", DisplayText: "Microsoft Excel", ExpertiseKeys: []string{"ops_admin_support", "finance_accounting"}},
	{SkillText: "airtable", DisplayText: "Airtable", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "zapier", DisplayText: "Zapier", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "make (integromat)", DisplayText: "Make (Integromat)", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "n8n", DisplayText: "n8n", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "data entry", DisplayText: "Data Entry", ExpertiseKeys: []string{"ops_admin_support"}},
	{SkillText: "transcription", DisplayText: "Transcription", ExpertiseKeys: []string{"ops_admin_support"}},

	// ---------------------------------------------------------------
	// legal (target ~25)
	// ---------------------------------------------------------------
	{SkillText: "droit des sociétés", DisplayText: "Droit des sociétés", ExpertiseKeys: []string{"legal"}},
	{SkillText: "droit commercial", DisplayText: "Droit commercial", ExpertiseKeys: []string{"legal"}},
	{SkillText: "droit du travail", DisplayText: "Droit du travail", ExpertiseKeys: []string{"legal", "hr_recruitment"}},
	{SkillText: "droit fiscal", DisplayText: "Droit fiscal", ExpertiseKeys: []string{"legal", "finance_accounting"}},
	{SkillText: "droit des contrats", DisplayText: "Droit des contrats", ExpertiseKeys: []string{"legal"}},
	{SkillText: "droit de la propriété intellectuelle", DisplayText: "Droit de la propriété intellectuelle", ExpertiseKeys: []string{"legal"}},
	{SkillText: "droit des marques", DisplayText: "Droit des marques", ExpertiseKeys: []string{"legal"}},
	{SkillText: "droit du numérique", DisplayText: "Droit du numérique", ExpertiseKeys: []string{"legal"}},
	{SkillText: "rgpd compliance", DisplayText: "RGPD Compliance", ExpertiseKeys: []string{"legal"}},
	{SkillText: "data protection officer (dpo)", DisplayText: "Data Protection Officer (DPO)", ExpertiseKeys: []string{"legal"}},
	{SkillText: "contract drafting", DisplayText: "Contract Drafting", ExpertiseKeys: []string{"legal"}},
	{SkillText: "contract review", DisplayText: "Contract Review", ExpertiseKeys: []string{"legal"}},
	{SkillText: "legal tech", DisplayText: "Legal Tech", ExpertiseKeys: []string{"legal"}},
	{SkillText: "compliance", DisplayText: "Compliance", ExpertiseKeys: []string{"legal", "finance_accounting"}},
	{SkillText: "conformité lcb-ft", DisplayText: "Conformité LCB-FT", ExpertiseKeys: []string{"legal", "finance_accounting"}},
	{SkillText: "litigation", DisplayText: "Litigation", ExpertiseKeys: []string{"legal"}},
	{SkillText: "arbitration", DisplayText: "Arbitration", ExpertiseKeys: []string{"legal"}},
	{SkillText: "mediation", DisplayText: "Mediation", ExpertiseKeys: []string{"legal"}},
	{SkillText: "due diligence juridique", DisplayText: "Due diligence juridique", ExpertiseKeys: []string{"legal"}},
	{SkillText: "rédaction de statuts", DisplayText: "Rédaction de statuts", ExpertiseKeys: []string{"legal"}},
	{SkillText: "cgv & cgu", DisplayText: "CGV & CGU", ExpertiseKeys: []string{"legal"}},
	{SkillText: "droit de la concurrence", DisplayText: "Droit de la concurrence", ExpertiseKeys: []string{"legal"}},
	{SkillText: "droit immobilier", DisplayText: "Droit immobilier", ExpertiseKeys: []string{"legal"}},
	{SkillText: "droit international des affaires", DisplayText: "Droit international des affaires", ExpertiseKeys: []string{"legal"}},
	{SkillText: "legal project management", DisplayText: "Legal Project Management", ExpertiseKeys: []string{"legal"}},
	{SkillText: "contentieux prud'homal", DisplayText: "Contentieux prud'homal", ExpertiseKeys: []string{"legal", "hr_recruitment"}},

	// ---------------------------------------------------------------
	// finance_accounting (target ~25)
	// ---------------------------------------------------------------
	{SkillText: "bookkeeping", DisplayText: "Bookkeeping", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "comptabilité générale", DisplayText: "Comptabilité générale", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "comptabilité analytique", DisplayText: "Comptabilité analytique", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "ifrs", DisplayText: "IFRS", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "us gaap", DisplayText: "US GAAP", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "plan comptable français", DisplayText: "Plan comptable français", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "déclarations tva", DisplayText: "Déclarations TVA", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "liasse fiscale", DisplayText: "Liasse fiscale", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "déclarations urssaf", DisplayText: "Déclarations URSSAF", ExpertiseKeys: []string{"finance_accounting", "hr_recruitment"}},
	{SkillText: "dsn (déclaration sociale nominative)", DisplayText: "DSN (Déclaration Sociale Nominative)", ExpertiseKeys: []string{"finance_accounting", "hr_recruitment"}},
	{SkillText: "bilan comptable", DisplayText: "Bilan comptable", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "management accounting", DisplayText: "Management Accounting", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "budget & forecasting", DisplayText: "Budget & Forecasting", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "cash flow management", DisplayText: "Cash Flow Management", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "financial reporting", DisplayText: "Financial Reporting", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "audit financier", DisplayText: "Audit financier", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "commissariat aux comptes", DisplayText: "Commissariat aux comptes", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "controlling", DisplayText: "Controlling", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "corporate finance", DisplayText: "Corporate Finance", ExpertiseKeys: []string{"finance_accounting", "consulting_strategy"}},
	{SkillText: "treasury management", DisplayText: "Treasury Management", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "credit analysis", DisplayText: "Credit Analysis", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "financial risk management", DisplayText: "Financial Risk Management", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "investor relations", DisplayText: "Investor Relations", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "transfer pricing", DisplayText: "Transfer Pricing", ExpertiseKeys: []string{"finance_accounting", "legal"}},
	{SkillText: "quickbooks", DisplayText: "QuickBooks", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "sage", DisplayText: "Sage", ExpertiseKeys: []string{"finance_accounting"}},
	{SkillText: "pennylane", DisplayText: "Pennylane", ExpertiseKeys: []string{"finance_accounting"}},

	// ---------------------------------------------------------------
	// hr_recruitment (target ~25)
	// ---------------------------------------------------------------
	{SkillText: "technical recruiting", DisplayText: "Technical Recruiting", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "executive search", DisplayText: "Executive Search", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "headhunting", DisplayText: "Headhunting", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "candidate sourcing", DisplayText: "Candidate Sourcing", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "boolean search", DisplayText: "Boolean Search", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "ats management", DisplayText: "ATS Management", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "greenhouse ats", DisplayText: "Greenhouse ATS", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "lever ats", DisplayText: "Lever ATS", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "recruitee", DisplayText: "Recruitee", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "employer branding", DisplayText: "Employer Branding", ExpertiseKeys: []string{"hr_recruitment", "marketing_growth"}},
	{SkillText: "candidate experience", DisplayText: "Candidate Experience", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "employee onboarding", DisplayText: "Employee Onboarding", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "employee offboarding", DisplayText: "Employee Offboarding", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "people operations", DisplayText: "People Operations", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "talent management", DisplayText: "Talent Management", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "performance management", DisplayText: "Performance Management", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "compensation & benefits", DisplayText: "Compensation & Benefits", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "payroll management", DisplayText: "Payroll Management", ExpertiseKeys: []string{"hr_recruitment", "finance_accounting"}},
	{SkillText: "hris administration", DisplayText: "HRIS Administration", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "workday", DisplayText: "Workday", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "bamboohr", DisplayText: "BambooHR", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "payfit", DisplayText: "PayFit", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "lucca", DisplayText: "Lucca", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "diversity & inclusion", DisplayText: "Diversity & Inclusion", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "learning & development", DisplayText: "Learning & Development", ExpertiseKeys: []string{"hr_recruitment"}},
	{SkillText: "hr analytics", DisplayText: "HR Analytics", ExpertiseKeys: []string{"hr_recruitment", "data_ai_ml"}},
	{SkillText: "labor relations", DisplayText: "Labor Relations", ExpertiseKeys: []string{"hr_recruitment", "legal"}},
}
